language = "C"

include_guard = "LASSO_H"
include_version = false

namespaces = []
using_namespaces = []

sys_includes = []
includes = []
no_includes = false
after_includes = ""
cpp_compat = true

braces = "SameLine"
line_length = 100
tab_width = 2
documentation_style = "auto"
line_endings = "LF"
style = "both"
sort_by = "Name"
usize_is_size_t = true

[defines]

[export]
include = []
exclude = []
item_types = []
renaming_overrides_prefixing = false

[export.rename]
"OpaqueRodeo" = "Rodeo"
"FFILassoErrorKind" = "LassoErrorKind"

[export.body]

[export.mangle]

[fn]
rename_args = "None"
args = "auto"
sort_by = "Name"

[struct]
rename_fields = "None"
derive_constructor = false
derive_eq = false
derive_neq = false
derive_lt = false
derive_lte = false
derive_gt = false
derive_gte = false

[enum]
rename_variants = "None"
add_sentinel = false
prefix_with_name = false
derive_helper_methods = false
derive_const_casts = false
derive_mut_casts = false
derive_tagged_enum_destructor = false
derive_tagged_enum_copy_constructor = false
enum_class = true
private_default_tagged_enum_constructor = false

[const]
allow_static_const = true
allow_constexpr = false
sort_by = "Name"

[macro_expansion]
bitflags = false

[parse]
parse_deps = false
include = []
exclude = []
clean = true
extra_bindings = []

[parse.expand]
crates = []
all_features = false
default_features = true
features = []
